# Site settings
title: EUR/SEK Serverless Forecasting System
description: Dashboard for EUR/SEK currency prediction and model performance
theme: jekyll-theme-minimal
logo: ./exchange-rate/logo.png

# Build settings
markdown: kramdown
