# Site settings
title: EUR SEK Exchange Rate Dashboard
description: Dashboard for EUR/SEK currency prediction and model performance
theme: jekyll-theme-minimal
logo: ./logo.png

# Build settings
markdown: kramdown
