- name: execute notebook
  env:
    HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
  run: |
    pip install nbconvert
    jupyter nbconvert \
      --to notebook \
      --execute 4_currency_batch_inference.ipynb \
      --output executed.ipynb

- name: list generated files
  run: |
    ls -R docs/exchange-rate/assets/img || echo "No images generated"

- name: github pages publish
  if: github.event_name == 'schedule'
  uses: stefanzweifel/git-auto-commit-action@v5
  with:
    commit_message: "Currency Prediction Dashboard published"
    file_pattern: 'docs/exchange-rate/assets/img/*'
